### PR TITLE
Add random smoke effect

### PR DESCRIPTION
**Pull request by jaspnas**
What were they smoking when the made this one

1 in 420 chance to show a smoke effect when loading any page

### CODE REVIEW

**Comment by JaninaHeikkala** [comment]
will this be on date website always from now on?

**Comment by jaspnas** [comment]
As the trigger is currently is set up, yes

If you have better ideas for trigger condition let me know

**Comment by JaninaHeikkala** [comment]
I'm thinking the smoke could appear only in this month and in the future in april (because 4.20 is in april (20th of april)). Or just keep it for a while for now :)

**Review by JaninaHeikkala — APPROVED** [review]
Looks good 420

**Pull request merged**
