### PR TITLE
Feat/pip compile + arm compat

### LINKED ISSUE #336: feat: Handle dependencies with pip-compile
Would be nice to not have to manage dependencies manually.

Maybe switch to a tool like [pip-compile](https://github.com/jazzband/pip-tools) to handle them for us.

### PR DESCRIPTION
**Pull request by jaspnas**
Closes #336 

Allow easily locking dependencies with pip-compile

Also fixes ARM compatibility.

### CODE REVIEW

**Comment by andreedd** [comment]
Sure, could try it out.

Maybe add to the readme some examples of using it?

**Comment by jaspnas** [comment]
Would maybe be a good idea to have Github actions regenerate the dependencies once a month and create a pull request, Then the smoketest-workflow from #344 should be enough to see if it breaks anything

**Comment by andreedd** [comment]
Yeah that could work, could even go as far as have actions do a commit with the dependencies at the same time if we want to.

**Comment by jaspnas** [comment]
> Yeah that could work, could even go as far as have actions do a commit with the dependencies at the same time if we want to.

Do we want to manually review it? Are we fine with breaking QA if we set up a CD pipeline from develop if the dependencies break something?

**Comment by andreedd** [comment]
I would say it is fine, since if we always commit them we can always revert them as easily as well.

**Comment by jaspnas** [comment]
Conflicting, will redo later

**Pull request closed without merging**
