### PR TITLE
Add option for banning gulisar from albums

### PR DESCRIPTION
**Pull request by WilliamNylund**

### CODE REVIEW

**Comment by vsjostro** [comment]
good job!

**Comment by WilliamNylund** [comment]
> good job!

Thank you @vsjostro for the kind words!

**Comment by vsjostro** [comment]
> > good job!
> 
> Thank you @vsjostro for the kind words!

no problem my good sir! keep up the good work!

**Review by andreedd — APPROVED** [review]
yes good boi

**Pull request merged**
