### PR TITLE
update to ckeditor 5

### LINKED ISSUE #509: fix: update CKeditor
**Is your fix request related to a problem?**  

> web_1     | ?: (ckeditor.W001) django-ckeditor bundles CKEditor 4.22.1 which isn't supported anmyore and which does have unfixed security issues, see for example https://ckeditor.com/cke4/release/CKEditor-4.24.0-LTS. You should consider strongly switching to a different editor (maybe CKEditor 5 respectively django-ckeditor-5 after checking whether the CKEditor 5 license terms work for you) or switch to the non-free CKEditor 4 LTS package. See https://ckeditor.com/ckeditor-4-support/ for more on this. (Note! This notice has been added by the django-ckeditor developers and we are not affiliated with CKSource and were not involved in the licensing change, so please refrain from complaining to us. Thanks.)

**Describe the solution you'd like**  
update the django-ckeditor dependency

**Additional context**  
The warning message appears when starting container.

### PR DESCRIPTION
**Pull request by Theoabw**

### CODE REVIEW

**Comment by jaspnas** [comment]
Text color is wrong in dark mode
image

Some options from the old editor like text color are missing, should be configurable
image
old editor:
image

**Review by jaspnas — DISMISSED** [review]
Please have a look at the styling issue for dark mode and the editor options

**Review by jaspnas — DISMISSED** [review]
image
Still needs more options for the editor.

see previous comment

**Comment by theoabw** [comment]
> image Still needs more options for the editor.
> 
> see previous comment

This was because of extends config not being specified in all places. I fixed it by making the extends config the default config. Should be fixed now.

**Review by jaspnas — APPROVED** [review]
Some things are still not the correct color in dark mode. Up to you if you want to fix now or open a new issue.

image
image
image

**Pull request merged**
